name: Deployment workflow
on: 
  push:
      branches:
        - main

jobs:
  build_client:
    name: Build client app
    runs-on: self-hosted
    steps:
      # - name: List files in the repository
      - run: |
          ls ${{ github.workspace }}
      # - name: Pull latest changes from main branches
      # - run: |
      #     git pull origin main
      # - name: Build client side
      # - run: |
      #     yarn client-build
      # - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."    
      # - run: echo "ğŸ This job's status is ${{ job.status }}."
